### ISSUE TITLE
hatched.SpatialPolygons bloque

### ISSUE THREAD

**Issue by coulmont** [statnmap/HatchedPolygons#1]
Exemple reproductible (R 3.6.0) qui bloque :

```
devtools::install_github("statnmap/HatchedPolygons")
library(HatchedPolygons)
library(tidyverse)
library(sp)
b <-  tribble(~xmin, ~ymin, ~xmax, ~ymax,
              650547.2, 6864883.8,  653940.0, 6867060.4 )
p1 <- rbind(c(b$xmin,b$ymin), c(b$xmax,b$ymin), c(b$xmax,b$ymax), c(b$xmin,b$ymax) , c(b$xmin,b$ymin))  
p1.sp <- SpatialPolygons(list(
  Polygons(list(Polygon(p1)), "1") ) )
xy.sp.hatch <- hatched.SpatialPolygons(p1.sp)
```

**Comment by statnmap** [comment]
Je pense que c'est la densité de lignes qui pose problème. ça ne plante pas mais c'est très long...   
Les tests que j'avais fait étaient avec des coordonnées géographiques, donc 0.5 lignes par degré (valeur par défaut) ça passe, mais 0.5 lignes par mètres, ça commence à faire beaucoup.
Ce code devrait être mieux:

```r
# devtools::install_github("statnmap/HatchedPolygons", force = TRUE)
library(HatchedPolygons)
library(tidyverse)
library(sp)
b <-  tribble(~xmin, ~ymin, ~xmax, ~ymax,
              650547.2, 6864883.8,  653940.0, 6867060.4 )
p1 <- rbind(c(b$xmin,b$ymin), c(b$xmax,b$ymin), c(b$xmax,b$ymax), c(b$xmin,b$ymax) , c(b$xmin,b$ymin))  
p1.sp <- SpatialPolygons(list(
  Polygons(list(Polygon(p1)), "1") ) )
xy.sp.hatch <- hatched.SpatialPolygons(p1.sp, density = 0.01)

plot(p1.sp)
plot(xy.sp.hatch, add = TRUE)
```

**Comment by coulmont** [comment]
Merci !
. . Baptiste Coulmont coulmont@gmail.com -------- 

    On Monday, July 1, 2019, 11:17:16 AM GMT+2, Sébastien Rochette <notifications@github.com> wrote:  
 
 
Je pense que c'est la densité de lignes qui pose problème. ça ne plante pas mais c'est très long...
Les tests que j'avais fait étaient avec des coordonnées géographiques, donc 0.5 lignes par degré (valeur par défaut) ça passe, mais 0.5 lignes par mètres, ça commence à faire beaucoup.
Ce code devrait être mieux:
# devtools::install_github("statnmap/HatchedPolygons", force = TRUE)
library(HatchedPolygons)
library(tidyverse)
library(sp)
b <-  tribble(~xmin, ~ymin, ~xmax, ~ymax,
              650547.2, 6864883.8,  653940.0, 6867060.4 )
p1 <- rbind(c(b$xmin,b$ymin), c(b$xmax,b$ymin), c(b$xmax,b$ymax), c(b$xmin,b$ymax) , c(b$xmin,b$ymin))  
p1.sp <- SpatialPolygons(list(
  Polygons(list(Polygon(p1)), "1") ) )
xy.sp.hatch <- hatched.SpatialPolygons(p1.sp, density = 0.01)

plot(p1.sp)
plot(xy.sp.hatch, add = TRUE)
