### ISSUE TITLE
possible with sf objects?

### ISSUE THREAD

**Issue by ghost** [statnmap/HatchedPolygons#2]
Hi,

I love your hatched polygons library, but I was wondering if there is a way to use it on sf rather than sp objects? I tried it with an sf data frame and it gave me an error "object 'pO' not found", even though I have no idea what pO is or what it's referring to. It works great on sp data frames, but I was just wondering if you were thinking about adding sf compatibility too.

Thanks!
James Cutler

**Comment by statnmap** [comment]
Thanks.  
I never took time to add this compatibility as pure {sf}. 
The only way for now is to transform {sf} to {sp} using `as(my_sf_obj, "Spatial")`  
And then the way back using `st_as_sf(my_hatched_obj)` as at the end of the blog post: https://statnmap.com/2017-05-23-how-to-fill-a-hatched-area-polygon-with-holes-in-leaflet-with-r/  
Maybe one day...

**Comment by ghost** [comment]
That's good to know. Thank you for getting back so quick! I love the
hatched polygons library, so thank you for sharing this amazing work!

Thanks,
James

**Comment by statnmap** [comment]
If this package inspires you to propose a pull request for a native compatibility with {sf}, I'll be happy to review it.

**Comment by ghost** [comment]
Well, when the day comes that I can call myself an R ninja capable of
something like that, then I will definitely think about it! Unfortunately a
project like that seems way over my head at the moment. But I hope to get
there one day! Any advice on how to take my coding skills to the next level
where I could do something like that? I've been using R for about 3 years,
and consider myself very familiar with it, but I honestly have no idea how
to do something like what you've done with the hatched polygons package.

Thanks!
James

**Comment by statnmap** [comment]
If you can write a code that works, then you can add it in a package. Then, this is a question of method. Here is my method : https://rtask.thinkr.fr/when-development-starts-with-documentation/

**Comment by ghost** [comment]
Wow! That's cool! This really makes writing my own package look easy!
Thanks!

**Comment by statnmap** [comment]
I partially updated the package to allow for hatched area directly with {sf}. Although this is a workaround that transforms as {sp}, then back to {sf}. But for now it does the job. More examples here in the vignette : https://statnmap.github.io/HatchedPolygons/articles/leaflet_shading_polygon.html

**Comment by ghost** [comment]
Awesome, thanks! I'll take a look at that soon for sure! I love this
hatched polygons package, thanks again for the good work!
