### ISSUE TITLE
Allow zero dashed lines when the polygon is too small

### ISSUE THREAD

**Issue by statnmap** [statnmap/HatchedPolygons#7]
Currently, the function fails when the density of dashed lines is too big considering the size of the polygon.  
Allow for empty geometry to avoid failing.  

Also, can propose an other value. See #6

**Comment by warnes** [comment]
This error is resolved by patch https://github.com/statnmap/HatchedPolygons/pull/9. It now generates this warning when a polygon is too small:
```
In polygonRingHolesLines(polys[[j]], density = density[j],  ... :
  Polygon too small to contain any lines.  Consider increasing 'density'.
```
